spring:
  datasource:
    #url: jdbc:mariadb://host.docker.internal:3306/jpa_db?useSSL=false
    #url: jdbc:mariadb://localhost:3306/jpa_db?useSSL=false
    url: jdbc:mariadb://mariadb_compose_container:3306/jpa_db?useSSL=false
    username: yhood
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none        #validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Table 매핑 대문자허용(지정한대로)
    properties:
      hibernate:
        show_sql: true
        format_sql: truez

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace